[workspace]
resolver = "2"
members =  [
  "implement",
  "tutorial1_window",
  "tutorial2_surface",
]

[workspace.dependencies]
env_logger = "0.10.0"
log = "0.4.20"
wgpu = "0.18.0"
winit = { version = "0.29.3", features = ["rwh_05"] }
pollster = "0.3.0"
